// Vectorizes the shirt logo: assets/logo.png -> assets/logo.svg + src/character/logo.js
//   node tools/trace-logo.mjs
// The small source image is upscaled (bilinear) before tracing so potrace can fit
// smooth curves instead of stair-steps. The path is centred on (0,0) and scaled to
// a unit height of 100 so the rig can size it freely.
import fs from 'node:fs';
import path from 'node:path';
import { PNG } from 'pngjs';
import potrace from 'potrace';
import { parsePath, transformContours, contoursToSvg, contoursBBox } from '../src/riv/path.js';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const src = PNG.sync.read(fs.readFileSync(path.join(ROOT, 'assets/logo.png')));
const K = 8; // upscale factor
const W = src.width * K, H = src.height * K;
// darkness 0..1 (transparent or light pixels count as paper)
const dark = (x, y) => {
  x = Math.max(0, Math.min(src.width - 1, x)); y = Math.max(0, Math.min(src.height - 1, y));
  const i = (y * src.width + x) * 4, a = src.data[i + 3] / 255;
  const lum = (src.data[i] + src.data[i + 1] + src.data[i + 2]) / 765;
  return a * (1 - lum);
};
const up = new PNG({ width: W, height: H });
for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
  const fx = x / K - 0.5, fy = y / K - 0.5, x0 = Math.floor(fx), y0 = Math.floor(fy), tx = fx - x0, ty = fy - y0;
  const v = dark(x0, y0) * (1 - tx) * (1 - ty) + dark(x0 + 1, y0) * tx * (1 - ty) + dark(x0, y0 + 1) * (1 - tx) * ty + dark(x0 + 1, y0 + 1) * tx * ty;
  const c = v > 0.5 ? 0 : 255, i = (y * W + x) * 4;
  up.data[i] = up.data[i + 1] = up.data[i + 2] = c; up.data[i + 3] = 255;
}
const d = await new Promise((res, rej) => {
  const t = new potrace.Potrace({ turdSize: 40 * K, alphaMax: 1.1, optCurve: true, optTolerance: 0.4, threshold: 128 });
  t.loadImage(PNG.sync.write(up), (err) => (err ? rej(err) : res(/ d="([^"]+)"/.exec(t.getPathTag())[1])));
});
let contours = parsePath(d);
const [x0, y0, x1, y1] = contoursBBox(contours);
const s = 100 / (y1 - y0), cx = (x0 + x1) / 2, cy = (y0 + y1) / 2;
contours = transformContours(contours, (x, y) => [(x - cx) * s, (y - cy) * s]);
const norm = contoursToSvg(contours, 2);
const w = ((x1 - x0) * s).toFixed(1);
fs.writeFileSync(path.join(ROOT, 'src/character/logo.js'),
  `// Generated by tools/trace-logo.mjs from assets/logo.png. Centred on (0,0), 100 units tall.\nexport const LOGO = { d: ${JSON.stringify(norm)}, width: ${w}, height: 100 };\n`);
fs.writeFileSync(path.join(ROOT, 'assets/logo.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${(-w / 2 - 4).toFixed(1)} -54 ${(+w + 8).toFixed(1)} 108"><path d="${norm}" fill="#141414" fill-rule="evenodd"/></svg>\n`);
console.log(`logo: ${contours.length} contour(s), ${contours.reduce((n, c) => n + c.points.length, 0)} points, ${w}x100`);
